name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip Project
        run: unzip game_project.zip

      - name: Build with Buildozer
        run: |
          # We use -u 1000 to run as a standard user instead of root
          docker run --rm \
            -u 1000 \
            -v ${{ github.workspace }}:/home/user/hostpython \
            -w /home/user/hostpython \
            kivy/buildozer \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk
